apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      default: https://github.com/omar-wanis/ci-cd-final-project.git
    - name: branch
      type: string
      default: main
    - name: build-image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/sn-labs-magdyomar039/counter-service:latest
    - name: app-name
      type: string
      default: counter-service
  tasks:
    - name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    - name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"
      runAfter:
        - cleanup

    - name: eslint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: eslint
      runAfter:
        - git-clone

    - name: jest-test
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: jest-test
      runAfter:
        - eslint

    - name: buildah
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.build-image)
        - name: DOCKERFILE
          value: ./Dockerfile
      runAfter:
        - jest-test

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            echo "Deploying $(params.app-name) ..."
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
            oc create service clusterip $(params.app-name) --tcp=8000:8000 --dry-run=client -o yaml | oc apply -f -
            oc expose service/$(params.app-name) || true
            oc rollout restart deployment/$(params.app-name)
            oc get deployment,service,route
      runAfter:
        - buildah
